/**
 * @file src/modules/volunteer/volunteer.constants.ts
 * @description Constants for the Volunteer Management module.
 */

export const VOLUNTEER_AUDIT_ACTIONS = {
  VOLUNTEER_CREATED: 'VOLUNTEER_CREATED',
  VOLUNTEER_UPDATED: 'VOLUNTEER_UPDATED',
  VOLUNTEER_STATUS_CHANGED: 'VOLUNTEER_STATUS_CHANGED',
  VOLUNTEER_ASSIGNED: 'VOLUNTEER_ASSIGNED',
  VOLUNTEER_DEACTIVATED: 'VOLUNTEER_DEACTIVATED',
  VOLUNTEER_REACTIVATED: 'VOLUNTEER_REACTIVATED',
} as const;
