export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  CHANGE_PASSWORD: '/change-password',
  NOTIFICATIONS: '/notifications',
  STUDENT: {
    DASHBOARD: '/student/dashboard',
    PROFILE: '/student/profile',
    VOLUNTEER_SUBMIT: '/student/volunteer-submit',
    VOLUNTEER_HISTORY: '/student/volunteer-history',
    RESUME: '/student/resume',
  },
  ZONE: {
    DASHBOARD: '/zone/dashboard',
    APPROVALS: '/zone/approvals',
    STUDENTS: '/zone/students',
    COLLEGES: '/zone/colleges',
    ANALYTICS: '/zone/analytics',
    PROFILE: '/zone/profile',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    PROVISIONING: '/admin/provisioning',
    STUDENTS: '/admin/students',
    ARCHIVED_STUDENTS: '/admin/archived-students',
    HIERARCHY: '/admin/hierarchy',
    ZONES: '/admin/zones',
    TEAM: '/admin/team',
    VOLUNTEERING_LOGS: '/admin/volunteering-logs',
    ANALYTICS: '/admin/analytics',
    AUDIT_LOGS: '/admin/audit-logs',
  },
} as const
